version: "3"
services:
  db:
    image: "postgres:11.1"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_USER=${POSTGRES_ROOT_USER}
    container_name: admindb
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      - "8889:5432"
